// Generated by diesel_ext

use chrono::NaiveDateTime;

#[derive(Queryable,Debug)]
pub struct Author {
    pub id: i32,
    pub value: Option<String>,
}

#[derive(Queryable,Debug)]
pub struct Branche {
    pub id: i32,
    pub value: Option<String>,
}

#[derive(Queryable,Debug)]
pub struct GithubIssue {
    pub id: i32,
    pub number: i32,
    pub title: String,
    pub body: String,
    pub labels: String,
    pub url: String,
}

#[derive(Queryable,Debug)]
pub struct GithubIssuesFetche {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub repo: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable,Debug)]
pub struct GithubPullFetche {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub repo: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable,Debug)]
pub struct GithubPull {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub number: i32,
    pub title: String,
    pub repo: String,
    pub body: String,
    pub labels: String,
    pub url: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable,Debug)]
pub struct GithubRepo {
    pub id: i32,
    pub repo: String,
    pub url: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable,Debug)]
pub struct Path {
    pub id: i32,
    pub value: Option<String>,
}

#[derive(Queryable,Debug)]
pub struct Project {
    pub id: i32,
    pub value: Option<String>,
}

#[derive(Queryable,Debug)]
pub struct ReplyTo {
    pub id: i32,
    pub value: Option<String>,
}

#[derive(Queryable,Debug)]
pub struct Rule {
    pub id: i32,
}

#[derive(Queryable,Debug)]
pub struct RulesAuthor {
    pub id: i32,
    pub key_id: Option<i32>,
    pub rule_id: Option<i32>,
}

#[derive(Queryable,Debug)]
pub struct RulesBranche {
    pub id: i32,
    pub key_id: Option<i32>,
    pub rule_id: Option<i32>,
}

#[derive(Queryable,Debug)]
pub struct RulesPath {
    pub id: i32,
    pub key_id: Option<i32>,
    pub rule_id: Option<i32>,
}

#[derive(Queryable,Debug)]
pub struct RulesProject {
    pub id: i32,
    pub key_id: Option<i32>,
    pub rule_id: Option<i32>,
}

#[derive(Queryable,Debug)]
pub struct RulesReplyTo {
    pub id: i32,
    pub key_id: Option<i32>,
    pub rule_id: Option<i32>,
}

#[derive(Queryable,Debug)]
pub struct RulesTo {
    pub id: i32,
    pub key_id: Option<i32>,
    pub rule_id: Option<i32>,
}

#[derive(Queryable,Debug)]
pub struct To {
    pub id: i32,
    pub value: Option<String>,
}

