// Generated by diesel_ext
#![allow(proc_macro_derive_resolution_fallback)]

extern crate chrono;

use self::chrono::NaiveDateTime;

use schema::{github_issues_fetches, github_pulls_fetches};

#[derive(Queryable, Debug)]
pub struct GithubIssue {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub number: i32,
    pub title: String,
    pub body: String,
    pub labels: String,
    pub url: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "github_issues_fetches"]
pub struct GithubIssuesFetch {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub repo: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct GithubPull {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub number: i32,
    pub title: String,
    pub repo: String,
    pub body: String,
    pub labels: String,
    pub url: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "github_pulls_fetches"]
pub struct GithubPullsFetch {
    pub github_repo_id: Option<i32>,
    pub id: i32,
    pub repo: String,
    pub data: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct GithubRepo {
    pub id: i32,
    pub repo: String,
    pub url: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub deleted_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Rule {
    pub id: i32,
    pub authors: Option<Vec<Option<String>>>,
    pub branches: Option<Vec<Option<String>>>,
    pub paths: Option<Vec<Option<String>>>,
    pub projects: Option<Vec<Option<String>>>,
    pub reply_to: Option<String>,
    pub to: Option<Vec<Option<String>>>,
}
